apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uit7nef8d-nodejs 
  janus-idp.io/tekton: uit7nef8d-nodejs
  backstage.io/kubernetes-id: uit7nef8d-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uit7nef8d-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  